# Generated by Django 2.1.4 on 2018-12-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181211_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='headline',
        ),
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.CharField(default='Creator', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_image',
            field=models.TextField(default='image'),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_url',
            field=models.TextField(default='url'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill1',
            field=models.CharField(default='url', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='skill1_level',
            field=models.CharField(default='url', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='skill2',
            field=models.CharField(default='url', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='skill2_level',
            field=models.CharField(default='url', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='skill3',
            field=models.CharField(default='url', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='skill3_level',
            field=models.CharField(default='url', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='skill4',
            field=models.CharField(default='url', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='skill4_level',
            field=models.CharField(default='url', max_length=50),
        ),
    ]
